// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"remoteworkout/internal/infra/web"
)

// Injectors from app_config.go:

func ProvideHttpServer() *web.HttpServer {
	httpServer := web.CreateHttpServer()
	return httpServer
}

func ProvideAppContext() *AppContext {
	httpServer := ProvideHttpServer()
	appContext := &AppContext{
		Server: httpServer,
	}
	return appContext
}

// app_config.go:

type AppContext struct {
	Server *web.HttpServer
}

var ContextSet = wire.NewSet(
	ProvideHttpServer, wire.Struct(new(AppContext), "*"),
)
